services:
  db:
    image: emmanueladb/any_post_db:latest
    container_name: any_post_db
    env_file:
      - .env  # Load environment variables from .env file
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    image: emmanueladb/any_post:latest
    container_name: any_post_app
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}?charset=UTF-8
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      UPLOAD_DIR: ${UPLOAD_DIR}
    ports:
      - "8080:8080"
    volumes:
      - uploads:/usr/local/tomcat/uploads  # Volume for uploads

volumes:
  postgres_data:
  uploads: